# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ind_wts.py
# Created on: 2018-07-12 20:12:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

def wts_extrat(dir_raster,acc_raster,point,snap_output,Watersh_as_d1,RasterT_Watersh1):
	"""Extract the polygon of a watershed from flow direction map and flow accumulation map.
    Args:
        dir_raster: the input file of a direction map
        acc_raster: the input file of an accumulation map
        point: the input file of a point object
		snap_output: the output file of the snap pour point
		Watersh_as_d1: the output file of the watershed raster
		RasterT_Watersh1: the output file of the watershed polygon
    Returns:
        None
    """
	# Process: 捕捉倾泻点
	arcpy.gp.SnapPourPoint_sa(point, acc_raster, snap_output, ".015", "id")
	# Process: 分水岭
	arcpy.gp.Watershed_sa(dir_raster, snap_output, Watersh_as_d1, "VALUE")
	# Process: 栅格转面
	arcpy.RasterToPolygon_conversion(Watersh_as_d1, RasterT_Watersh1, "SIMPLIFY", "VALUE")
	return None

## input gis objects
dir_raster = "input\\as_dir_15s\\as_dir_15s"
acc_raster = "input\\as_acc_15s\\as_acc_15s"
i=66193 # id (or file name) of the watershed
point = "input\\point\\"+str(i)+".shp"

## output gis objects
snap_output = "output\\snap\\"+str(i)
Watersh_as_d1 = "output\\wts_raster\\"+str(i)
RasterT_Watersh1 = "output\\wts_polygon\\"+str(i)+".shp"

wts_extrat(dir_raster,acc_raster,point,snap_output,Watersh_as_d1,RasterT_Watersh1)


	
